

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: selimdhib1999
      MYSQL_DATABASE: testauth
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: springboot-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testauth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: selimdhib1999
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  mice-frontend:
    image: mice-frontend
    depends_on:
      - app
    ports:
      - "4200:80"

volumes:
  db_data:
